### ISSUE TITLE
Provide a zip of all pdf's

### ISSUE THREAD

**Issue by aviaryan** [dufferzafar/geeks-pdf#2]
There are almost 25 pdf's there. It's very tedious to download them one by one. It would be nice if you provide a zip of them **too**.

**Comment by dufferzafar** [comment]
[Done!](https://github.com/dufferzafar/geeks-pdf/releases/tag/v1.1)

From now on I'll just upload an updated PDF of a single topic.

**Comment by dufferzafar** [comment]
Also, Never (ever) do tedious stuff. [That's what computers are for.](http://downthemall.net/) :wink:

**Comment by nickedes** [comment]
:+1: :heart_eyes:

**Comment by aviaryan** [comment]
:+1: :joy: :sweat_smile:
